---
name: Temporary Build
on: 
  push:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.5'
      - run: yarn install
      - run: yarn build
        env:
          REACT_APP_API_ROOT: "https://planetarycomputer.microsoft.com"
          REACT_APP_AZMAPS_KEY: ${{ secrets.REACT_APP_AZMAPS_KEY }}
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
          sync: 'false'
          overwrite: 'true'
